{
  "driver": {
    "name": "vagrant"
  },
  "provisioner": {
  name: chef_zero,
  require_chef_omnibus: 12.4.0
  },
  "platforms": [
    {
      "name": "centos-7.0",
      "driver": {
        "box": "centos70",
        "box_url": "file:////nfs/slac/g/scs/redhat.Images/vagrant/centos70-cheflatest.box"
      }
    },
    {
      "name": "rhel-7.1",
      "driver": {
        "box": "rhel71chef",
        "box_url": "file:///nfs/slac/g/scs/redhat.Images/vagrant/rhel7.1-cheflatest.box"
      }
    }
  ],
  "suites": [
    {
      "name": "default",
      "run_list": "recipe[slac_test::default]",
      "attributes": null
    }
  ]
}
